---

- name: install httpd-tools
  package:
    name: httpd-tools

- name: add user to htpasswd
  community.general.htpasswd:
    path: /etc/nginx/conf.d/.htpasswd
    user: '{{ nginx.htpasswd.user }}'
    password: '{{ nginx.htpasswd.pass }}'
    owner: root
    group: nginx
    mode: '0640'
