---

- name: yum clean all
  shell: 'yum clean all'
  when: ansible_os_family == "RedHat"

- name: let's use the closest centos mirror
  file:
    path: /var/cache/yum/x86_64/7/timedhosts.txt
    state: absent
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: let's use the fastest mirror
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'fastestmirror=1'
    insertafter: '^gpgcheck'
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "8"

- name: makecache on RedHat
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: ensure EPEL repository for RedHat/CentOS
  package:
    name: epel-release
  when: ansible_os_family == "RedHat"

- name: ensure we have a few packages
  package:
    name: ['git', 'java-{{ trsa.java.version }}-openjdk-devel', 'jq']
  when: ansible_os_family == "RedHat"
